spring:
  application:
    name: redis-as-database
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    repositories:
      enabled: true 

logging:
  config: classpath:logback-spring.xml
  level:
    org.fsk.redisasdatabase: DEBUG
    org.springframework: INFO
